name: Run devtools::check on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-devtools-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.3"

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("devtools", "remotes"))'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Run devtools::check
      run: |
        Rscript -e 'devtools::check()'
