name: R CMD Check

on:
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      # Step 3: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev pandoc

      # Step 4: Create a user library path and set permissions
      - name: Set up R library path
        run: |
          mkdir -p "$HOME/R/library"
          echo 'R_LIBS_USER=$HOME/R/library' >> $GITHUB_ENV

      # Step 5: Install devtools
      - name: Install devtools
        run: |
          Rscript -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'

      # Step 6: Install R package dependencies
      - name: Install R package dependencies
        run: |
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      # Step 7: Run devtools::check()
      - name: Run R CMD Check
        run: |
          Rscript -e 'devtools::check()'
